from turtle import*
import turtle

hideturtle()
s=int(input("Enter the length of the side of square: "))
h=int(input("Enter height of something: "))
forward(s)
left(90)
forward(h)
left(90)
forward(s)
left(90)
forward(h)
penup()
left(180)
forward(h)
pendown()
right(30)
forward(s)
right(120)
forward(s)
exitonclick()