from turtle import*
import turtle
bgcolor("#FFFF00")
penup()
forward(-200)
pendown()
turtle.color("#FF6BDE")
style = ('Arial', 30, 'italic')
turtle.write('Kenneth', font=style, align='center')
turtle.hideturtle()
penup()
forward(200)
pendown()
turtle.color("#00FF00")
style = ('Arial', 60, 'italic')
turtle.write('Tuisk', font=style, align='center')
turtle.hideturtle()
exitonclick()